version: '3'
services:
  frontend:
    build:
      context: ./cooperfilme_front
    ports:
      - "3000:3000"  # Porta 3000 para o React
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./cooperfilme
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cooperfilme
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    networks:
      - backend-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cooperfilme
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
